[workspace]
members = [
  "parse",
  "typecheck",
  "symbol_table",
  "codegen",
  "compiler",
  "runtime"
]

[profile.release]
lto = "fat"

[profile.release-with-debug]
inherits = "release"
debug = true
