[package]
name = "typecheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
immutable-map = "0.1.2"
parse = {path = "../parse"}
symbol_table = {path = "../symbol_table"}
